Adjust recaptcha score threshold
kbytesys/django-recaptcha3 pull request #2
Opened 2018-11-20 07:19 UTC by mtb-beta

- I'd like to use the score included in the recaptcha v3 response.
- Add debug log to adjust score.

2018-11-23 00:06 UTC, kbytesys requested changes
I'm sorry but I have to ask you another change.

This sentence is from the recaptha3 documentation

> "By default, you can use a threshold of 0.5."

Could please use this default value and update the readme.md with the new value?

Thanks!

2018-11-23 00:06 UTC, kbytesys commented on snowpenguin/django/recaptcha3/fields.py
> +        self._score_threshold = getattr(settings, 'RECAPTCHA_SCORE_THRESHOLD', 0)
It could be nice if the the developer can choose the _score_threshold as we do few lines above with the 'private_key' parameter.

Could you update your code with this change?

Thanks!

2018-11-24 03:47 UTC, mtb-beta commented
> Could please use this default value and update the readme.md with the new value?

The score distribution is not clear until reaptcha v3 starts the service.
For safe deployment, I think that it is better to first check only the token.
I think the default value of django-recaptcha3 should be None.
What do you think about this?

2018-11-24 22:23 UTC, kbytesys commented
> The score distribution is not clear until reaptcha v3 starts the service.
> For safe deployment, I think that it is better to first check only the token.
> I think the default value of django-recaptcha3 should be None.
> What do you think about this?

We can mix your previous commits with the new one. What do you think if we bring back the idea about to set the default score in the application configuration?

something like this just to be clear:

`self._score_threshold = kwargs.pop('score_threshold', settings.RECAPTCHA_SCORE_THRESHOLD)`

What do you think?

2018-11-26 09:27 UTC, mtb-beta commented
OK. I think that is all right.

I fixed the code. please confirm. 

Thank you.

2018-11-26 13:55 UTC, merged